{% set goname = "github.com/jaegertracing/jaeger" %}
{% set version = "1.21.0" %}
{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/' + goname).replace("/", os.sep) %}

{% set goname_ui = "github.com/jaegertracing/jaeger-ui" %}
{% set version_ui = "1.12.0" %}
{% set pkg_src_ui = ('src/' + goname + '/jaeger-ui').replace("/", os.sep) %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz
    sha256: 9361adeec029ab643e4cf0a451403649daa8e9e687291fc04a50d7e9a1732b82
    patches:
      - git.patch
  - folder: {{ pkg_src_ui }}
    url: https://{{ goname_ui }}/archive/v{{ version_ui }}.tar.gz
    sha256: 2b4f2fb35516360d0ad0e308365f351ae3cf4c20455f2e1dc72d3493baf476b1

build:
  number: 0
  binary_relocation: false
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}
    - go-licenses
    - make
  host:
    - go-dep
    - nodejs
    - yarn

test:
  commands:
    - jaeger-agent --help
    - jaeger-all-in-one --help
    - jaeger-collector --help
    - jaeger-hotrod --help
    - jaeger-ingester --help
    - jaeger-query --help
    - jaeger-tracegen --help

about:
  home: https://www.jaegertracing.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: CNCF Jaeger, a Distributed Tracing Platform

  description: |
    Jaeger, inspired by Dapper and OpenZipkin, is a distributed tracing system
    released as open source by Uber Technologies.
    It is used for monitoring and troubleshooting microservices-based
    distributed systems.
  doc_url: https://www.jaegertracing.io/docs
  dev_url: https://github.com/jaegertracing/jaeger

extra:
  recipe-maintainers:
    - saulshanabrook
    - goanpeca
    - bollwyvl
